name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Build
        run: cargo build --release

      - name: Sign Binary
        run: openssl dgst -sha256 -sign private.pem -out rust-service.sig rust-service/target/release/rust-service

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-service
          path: rust-service/target/release/rust-service
